### ISSUE TITLE
Support for STDERR

### ISSUE THREAD

**Issue by kuryaki** [ovhemert/pino-papertrail#19]
Right now it only streams the stdout not the stderr, is it because of any particular technical constraint?

**Comment by ovhemert** [comment]
Pino outputs all the log messages, including errors (level >= 50) to `stdout`. You can read the explanation for that [here](https://github.com/pinojs/pino/blob/master/docs/transports.md#in-process-transports).
That means that all messages can be piped to a transport using the same stream. This library/transport follows the same pattern, because it expects the errors also to come from the `stdout` stream in the pino json format.

**Comment by kuryaki** [comment]
Yup, I ended sending the stderr to stdout and got it from there :+1:
